### ISSUE TITLE
Planejamento - Demo

### ISSUE THREAD

**Issue by gabrielgomes94** [gabrielgomes94/just-one-more-turn#25]
- Objetivo: entregar uma versão demo do jogo na versão 0.1

### Milestones pra demo:
- [x] 0.0.0 Hex
- [ ] 0.0.1 Cidades e impérios
- [ ] 0.0.2 Câmera e telas do jogo
- [ ] 0.0.3 Recursos e consumo
- [ ] 0.0.4 Unidades, movimentação e pathfinding
- [ ] 0.0.5 Combate
- [ ] 0.0.6 Adversários e IA
- [ ] 0.0.7 Monstros
- [ ] 0.0.8 Trocas e comércio
- [ ] 0.0.9 Melhorias no mapa
- [ ] 0.0.10 Geração procedural de mapas
- [ ] 0.0.11 Condições de vitória e Game Over
- [ ] 0.0.12 Menu e ajustes de UI
