### ISSUE TITLE
Criar label de UI com nome da cidade

### ISSUE THREAD

**Issue by gabrielgomes94** [gabrielgomes94/just-one-more-turn#27]
Criar label para as cidades do jogo, com o Nome e o tamanho da população. 
Usar de inspiração o jeito que o Civilization faz: 

![image](https://user-images.githubusercontent.com/9309745/90052765-ff5e9e80-dcaf-11ea-9183-517d25bfa4a3.png)

---

### Tasks

- [x] Criar Canvas no mapa de jogo
- [x] Criar Prefab para o Label da cidade
- [x] Posicionar corretamente o Label em relação a um ponto no mapa. 
- [x] Organizar o componente de UI: namespaces e assembly definition
- [x] Implementar Evento que é disparado durante a criação de cidades: criar o label em cima da cidade ao criar uma cidade
- [x] Adicionar botão na área da UI. Se o jogador clicar no botão, seleciona a cidade. 

---
![image](https://user-images.githubusercontent.com/9309745/90129471-1ac4ba80-dd3f-11ea-8367-40f90394217f.png)

**Comment by gabrielgomes94** [comment]
### Observações - 14/08/2020:  

- PR: https://github.com/gabrielgomes94/just-one-more-turn/pull/28
- A história vai ficar bloqueada até as dependências do módulo Hex serem estruturadas e organizadas: https://github.com/gabrielgomes94/just-one-more-turn/issues/29

###### Esforço: 2 ciclos
